refactor(gpu): remove memory pool allocator
This resolves an error where the deconvolution would fail on subsequent
runs with the error message (full traceback at the bottom):

```python
cupy.cuda.cufft.CuFFTError: CUFFT_EXEC_FAILED
```

The memory pool could perhaps be released or cleared or something, but
this does solve the issue without causing a noticeable change in
execution speed. I'm not sure what the original need was for the
inclusion of the pool.

```python
Traceback (most recent call last):
  File "/media/fusion/fusion-files/een023/project/src/fourier_noise_downsample_signal.py", line 157, in <module>
    res_d, err_d = dec.RL_gauss_deconvolve(
  File "/media/fusion/fusion-files/een023/project/.pixi/envs/default/lib/python3.10/site-packages/fppanalysis/deconvolution_methods.py", line 126, in RL_gauss_deconvolve
    (signal_temporary - fftconvolve(updated_result, kern_temporary, "same"))
  File "/media/fusion/fusion-files/een023/project/.pixi/envs/default/lib/python3.10/site-packages/cupyx/scipy/signal/signaltools.py", line 178, in fftconvolve
    out = _st_core._freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)
  File "/media/fusion/fusion-files/een023/project/.pixi/envs/default/lib/python3.10/site-packages/cupyx/scipy/signal/_signaltools_core.py", line 166, in _freq_domain_conv
    sp2 = fftn(in2, fshape, axes=axes)
  File "/media/fusion/fusion-files/een023/project/.pixi/envs/default/lib/python3.10/site-packages/cupyx/scipy/fft/_fft.py", line 466, in rfftn
    return func(x, s, axes, norm, cufft.CUFFT_FORWARD, 'R2C',
  File "/media/fusion/fusion-files/een023/project/.pixi/envs/default/lib/python3.10/site-packages/cupy/fft/_fft.py", line 247, in _fft
    a = _exec_fft(a, direction, value_type, norm, axes[-1], overwrite_x)
  File "/media/fusion/fusion-files/een023/project/.pixi/envs/default/lib/python3.10/site-packages/cupy/fft/_fft.py", line 190, in _exec_fft
    plan.fft(a, out, direction)
  File "cupy/cuda/cufft.pyx", line 500, in cupy.cuda.cufft.Plan1d.fft
  File "cupy/cuda/cufft.pyx", line 520, in cupy.cuda.cufft.Plan1d._single_gpu_fft
  File "cupy/cuda/cufft.pyx", line 1144, in cupy.cuda.cufft.execD2Z
  File "cupy/cuda/cufft.pyx", line 169, in cupy.cuda.cufft.check_result
cupy.cuda.cufft.CuFFTError: CUFFT_EXEC_FAILED
```